# Generated by Django 2.1.5 on 2021-11-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Course_Number', models.IntegerField(blank=True, default='', max_length=60)),
                ('Instructor_Name', models.TextField(blank=True, default='', max_length=300)),
                ('Duration', models.DurationField()),
            ],
        ),
    ]
