# Generated by Django 2.1.5 on 2021-11-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
