# Generated by Django 2.1.5 on 2021-11-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20211107_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Instructor_Name',
            field=models.TextField(max_length=300),
        ),
    ]
